#               Makefile for
#               MicroEMACS 4.00
#               (C)Copyright 1995 by Daniel Lawrence
#               all rights reserved

# This makefile is appropriate for *very early* UNIX systems like 4.1 BSD.
# It is possible to test it on SunOS 5.7 (not an early UNIX) using the step described below.

# modify the following lines with the proper relative directories

# object file directory
OBJD = .
# source file directory
SRCD = ../src
# header file directory
HDIR = ../h

# options and arguments to the C compiler
##
#CFLAGS = -I. -I$(HDIR) -DPROTO=0 -DUSE_STDARG=0
#CFLAGS = -I. -I$(HDIR)
##
#CFLAGS = -I. -I$(HDIR) -O -DPROTO=0 -DUSE_STDARG=0
#CFLAGS = -I. -I$(HDIR) -O

# This is the SunOS 5.7 command line:
# To test on SunOS follow these steps:
# $ mkdir sys
# $ ln -s /usr/include/sys/dirent.h sys/dir.h
#CFLAGS = -Wall -Wno-unused -I. -I$(HDIR) -O -DUMC_DIRENTRY=dirent -DPROTO=0 -DUSE_STDARG=0
# should be the same as
CFLAGS = -Wall -Wno-unused -I. -I$(HDIR) -O -DUMC_DIRENTRY=dirent
# This is the BSD 4.1 command line:
#CFLAGS = -I. -I$(HDIR) -O
##


# list of header files

HFILES = estruct.h $(HDIR)/ebind.h $(HDIR)/edef.h           \
          $(HDIR)/elang.h $(HDIR)/epath.h $(HDIR)/eproto.h

#list of object files

F1 = $(OBJD)/abbrev.o $(OBJD)/ansi.o $(OBJD)/basic.o $(OBJD)/bind.o     \
      $(OBJD)/buffer.o
F2 = $(OBJD)/char.o $(OBJD)/crypt.o $(OBJD)/display.o $(OBJD)/dolock.o
F3 = $(OBJD)/eval.o $(OBJD)/exec.o $(OBJD)/file.o $(OBJD)/fileio.o
F4 = $(OBJD)/input.o $(OBJD)/isearch.o $(OBJD)/keyboard.o $(OBJD)/line.o
F5 = $(OBJD)/lock.o $(OBJD)/main.o $(OBJD)/mouse.o $(OBJD)/screen.o
F6 = $(OBJD)/random.o $(OBJD)/region.o $(OBJD)/search.o $(OBJD)/replace.o
F7 = $(OBJD)/tags.o $(OBJD)/undo.o $(OBJD)/unixsys.o $(OBJD)/unixterm.o \
      $(OBJD)/window.o $(OBJD)/word.o
F8 = $(OBJD)/elang.o

# product list

all:	emacs

OFILES = $(F1) $(F2) $(F3) $(F4) $(F5) $(F6) $(F7) $(F8)

emacs:	$(OFILES)
	$(CC) $(CFLAGS) $(OFILES) $(LIB_TERMCAP) -lc -o emacs

$(OBJD)/abbrev.o: $(SRCD)/abbrev.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/abbrev.c
$(OBJD)/ansi.o: $(SRCD)/ansi.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/ansi.c
$(OBJD)/basic.o: $(SRCD)/basic.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/basic.c
$(OBJD)/bind.o: $(SRCD)/bind.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/bind.c
$(OBJD)/buffer.o: $(SRCD)/buffer.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/buffer.c
$(OBJD)/char.o: $(SRCD)/char.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/char.c
$(OBJD)/crypt.o: $(SRCD)/crypt.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/crypt.c
$(OBJD)/cmdfix.o: $(SRCD)/cmdfix.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/cmdfix.c
$(OBJD)/display.o: $(SRCD)/display.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/display.c
$(OBJD)/dolock.o: $(SRCD)/dolock.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/dolock.c
$(OBJD)/elang.o: $(SRCD)/elang.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/elang.c
$(OBJD)/eval.o: $(SRCD)/eval.c $(HFILES) $(HDIR)/evar.inc
	$(CC) $(CFLAGS) -c $(SRCD)/eval.c
$(OBJD)/exec.o: $(SRCD)/exec.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/exec.c
$(OBJD)/file.o: $(SRCD)/file.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/file.c
$(OBJD)/fileio.o: $(SRCD)/fileio.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/fileio.c
$(OBJD)/input.o: $(SRCD)/input.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/input.c
$(OBJD)/isearch.o: $(SRCD)/isearch.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/isearch.c
$(OBJD)/keyboard.o: $(SRCD)/keyboard.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/keyboard.c
$(OBJD)/line.o: $(SRCD)/line.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/line.c
$(OBJD)/lock.o: $(SRCD)/lock.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/lock.c
$(OBJD)/main.o: $(SRCD)/main.c $(HFILES) $(HDIR)/efunc.inc
	$(CC) $(CFLAGS) -c $(SRCD)/main.c
$(OBJD)/mouse.o: $(SRCD)/mouse.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/mouse.c
$(OBJD)/random.o: $(SRCD)/random.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/random.c
$(OBJD)/region.o: $(SRCD)/region.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/region.c
$(OBJD)/screen.o: $(SRCD)/screen.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/screen.c
$(OBJD)/search.o: $(SRCD)/search.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/search.c
$(OBJD)/replace.o: $(SRCD)/replace.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/replace.c
$(OBJD)/tags.o: $(SRCD)/tags.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/tags.c
$(OBJD)/undo.o: $(SRCD)/undo.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/undo.c
$(OBJD)/unixsys.o: $(SRCD)/unixsys.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/unixsys.c
$(OBJD)/unixterm.o: $(SRCD)/unixterm.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/unixterm.c
$(OBJD)/window.o: $(SRCD)/window.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/window.c
$(OBJD)/word.o: $(SRCD)/word.c $(HFILES)
	$(CC) $(CFLAGS) -c $(SRCD)/word.c


clean:
	rm -f *.o
	rm -f emacs


# EOF
